### ISSUE TITLE
Playbook to apply VLAN settings based on NetBox

### ISSUE THREAD

**Issue by mi2428** [yamaoka-kitaguchi-lab/tn4-edges-deploy#3]
## Tasks
- [ ] Add dynamic inventory script
- [ ] **Get inventory only when its status is active**
- [ ] Backup config
- [ ] Add config templates
